export const stylesB = {
  loginWrap: { display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", padding: 20 },
  loginCard: { background: "#1a1a1a", borderRadius: 20, padding: "32px 26px", maxWidth: 340, width: "100%", textAlign: "center", boxShadow: "0 8px 28px rgba(0,0,0,0.5)", border: "1.5px solid #2a2a2a" },
  loginTitle: { fontSize: 20, fontWeight: 800, marginBottom: 6, color: "#f0f0f0" },
  loginSub: { fontSize: 13, color: "#9a9a9a" },
  btnLink: { background: "none", border: "none", color: "#9a9a9a", fontSize: 12.5, fontWeight: 600, cursor: "pointer", marginTop: 14, fontFamily: "'Poppins', sans-serif", textDecoration: "underline" },
  headerAdmin: { background: "#1a1a1a", boxShadow: "0 2px 12px rgba(0,0,0,0.4)", borderBottom: "2px solid #2a4a2e", position: "sticky", top: 0, zIndex: 100 },
  headerAdminRow: { maxWidth: 760, margin: "0 auto", padding: "12px 16px 0", display: "flex", alignItems: "center", gap: 10 },
  logoCircleAdmin: { width: 38, height: 38, borderRadius: 10, background: "linear-gradient(135deg, #2ecc40 0%, #1e8e2c 100%)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 19, flexShrink: 0, boxShadow: "0 4px 12px rgba(46,204,64,0.25)" },
  adminTitulo: { fontSize: 18, fontWeight: 800, color: "#2ecc40" },
  adminSub: { fontSize: 10, fontWeight: 700, color: "#9a9a9a", letterSpacing: 1.5, textTransform: "uppercase" },
  adminNav: { display: "flex", gap: 1, padding: "0 10px", marginTop: 8, overflowX: "auto", maxWidth: 760, margin: "8px auto 0" },
  adminNavBtn: { background: "none", border: "none", borderBottom: "3px solid transparent", padding: "9px 13px", cursor: "pointer", fontSize: 12, fontWeight: 600, color: "#9a9a9a", whiteSpace: "nowrap", fontFamily: "'Poppins', sans-serif" },
  adminNavBtnActive: { color: "#2ecc40", borderBottomColor: "#2ecc40" },
  h2: { fontSize: 21, fontWeight: 800, color: "#f0f0f0", marginBottom: 10, display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", maxWidth: 760 },
  h3: { fontSize: 11, fontWeight: 700, color: "#9a9a9a", textTransform: "uppercase", letterSpacing: 1, margin: "22px 0 10px" },
  hint: { fontSize: 12.5, color: "#9a9a9a", marginBottom: 16, maxWidth: 760, lineHeight: 1.5 },
  card: { background: "#1a1a1a", borderRadius: 14, padding: 18, boxShadow: "0 2px 12px rgba(0,0,0,0.35)", border: "1.5px solid #2a2a2a", marginBottom: 18, maxWidth: 760 },
  cardTitle: { fontSize: 14, fontWeight: 700, color: "#9a9a9a", marginBottom: 14 },
  formGrid2: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 10 },
  label: { fontSize: 10, fontWeight: 700, color: "#9a9a9a", textTransform: "uppercase", letterSpacing: 0.5, display: "block", marginBottom: 5 },
  input: { width: "100%", border: "1.5px solid #2a2a2a", borderRadius: 10, padding: "11px 12px", fontSize: 15, fontFamily: "'Poppins', sans-serif", background: "#161616", color: "#f0f0f0", outline: "none", boxSizing: "border-box" },
  btn: { background: "#2ecc40", color: "#06170a", border: "none", borderRadius: 10, padding: "11px 20px", fontWeight: 700, fontSize: 14, cursor: "pointer", fontFamily: "'Poppins', sans-serif", width: "100%" },
  btnSec: { background: "transparent", color: "#2ecc40", border: "1.5px solid #2ecc40", borderRadius: 10, padding: "9px 14px", fontWeight: 700, fontSize: 12.5, cursor: "pointer", fontFamily: "'Poppins', sans-serif" },
  btnSecSmall: { background: "transparent", color: "#2ecc40", border: "1.5px solid #2ecc40", borderRadius: 8, padding: "7px 12px", fontWeight: 700, fontSize: 12, cursor: "pointer", fontFamily: "'Poppins', sans-serif" },
  btnDanger: { background: "#3a1414", color: "#ff5c5c", border: "1px solid #5c2424", borderRadius: 6, padding: "6px 12px", fontSize: 12, cursor: "pointer", fontWeight: 600, fontFamily: "'Poppins', sans-serif" },
  btnOutline: { background: "transparent", color: "#ff5c5c", border: "1.5px solid #ff5c5c", borderRadius: 10, padding: "10px 16px", fontWeight: 700, fontSize: 13, cursor: "pointer", fontFamily: "'Poppins', sans-serif" },
  btnImprimir: { marginTop: 10, width: "100%", background: "transparent", color: "#9a9a9a", border: "1px solid #2a2a2a", borderRadius: 8, padding: "8px 0", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "'Poppins', sans-serif" },
  fotoUploadBox: { width: "100%", height: 140, background: "#161616", border: "2px dashed #2a2a2a", borderRadius: 14, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", overflow: "hidden" },
  fotoUploadPreview: { width: "100%", height: "100%", objectFit: "cover" },
  prodItem: { background: "#1a1a1a", borderRadius: 12, padding: 14, boxShadow: "0 2px 12px rgba(0,0,0,0.35)", border: "1.5px solid #2a2a2a", marginBottom: 10, maxWidth: 760 },
  prodItemPausado: { opacity: 0.5 },
  prodTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  prodThumb: { width: 52, height: 52, borderRadius: 10, objectFit: "cover", flexShrink: 0 },
  prodNome: { fontWeight: 700, fontSize: 15, color: "#f0f0f0" },
  prodCatTag: { fontSize: 10, fontWeight: 700, color: "#2ecc40", background: "#163320", padding: "2px 8px", borderRadius: 10, marginLeft: 6 },
  prodDesc: { fontSize: 13, color: "#9a9a9a", marginTop: 4, lineHeight: 1.4 },
  prodPreco: { fontWeight: 700, fontSize: 16, color: "#2ecc40", whiteSpace: "nowrap" },
  prodActions: { display: "flex", gap: 8, marginTop: 10, alignItems: "center", flexWrap: "wrap" },
  switch: { position: "relative", display: "inline-block", width: 42, height: 24, flexShrink: 0, cursor: "pointer" },
  slider: { position: "absolute", inset: 0, borderRadius: 24, transition: "0.2s" },
  sliderDot: { position: "absolute", height: 18, width: 18, left: 3, bottom: 3, background: "#fff", borderRadius: "50%", transition: "0.2s", display: "block" },
  pedidoCard: { background: "#1a1a1a", borderRadius: 12, padding: 14, boxShadow: "0 2px 12px rgba(0,0,0,0.35)", border: "1.5px solid #2a2a2a", marginBottom: 10, maxWidth: 760 },
  pedidoTop: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  pedidoNome: { fontWeight: 700, fontSize: 14, color: "#f0f0f0" },
  pedidoData: { fontSize: 11, color: "#9a9a9a" },
  pedidoTotal: { fontWeight: 800, color: "#2ecc40", fontSize: 15, marginTop: 4 },
  pedidoDetail: { fontSize: 12.5, color: "#9a9a9a", marginTop: 6, lineHeight: 1.5 },
  pedidoTag: { fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 10, background: "#163320", color: "#2ecc40" },
  linkPreview: { display: "flex", alignItems: "center", gap: 10, background: "#163320", borderRadius: 10, padding: "12px 14px", fontSize: 13, color: "#2ecc40", fontWeight: 600, marginTop: 6 },
  modalBg: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", zIndex: 998, display: "flex", alignItems: "center", justifyContent: "center" },
  modal: { background: "#1a1a1a", borderRadius: 20, padding: 24, margin: 20, maxWidth: 340, width: "100%", textAlign: "center", border: "1px solid #2a2a2a" },
  modalTitulo: { fontSize: 18, fontWeight: 800, marginBottom: 8, color: "#f0f0f0" },
  modalTexto: { fontSize: 14, color: "#9a9a9a", marginBottom: 20 },
  modalBtnCancelar: { flex: 1, padding: 12, borderRadius: 10, fontWeight: 700, fontSize: 14, cursor: "pointer", fontFamily: "'Poppins', sans-serif", border: "none", background: "#252525", color: "#ddd" },
  modalBtnConfirmar: { flex: 1, padding: 12, borderRadius: 10, fontWeight: 700, fontSize: 14, cursor: "pointer", fontFamily: "'Poppins', sans-serif", border: "none", background: "#dc2626", color: "#fff" },
};